### ISSUE TITLE
Where is category data processed

### ISSUE THREAD

**Issue by abubakar12** [rjfs/kaggle#1]
When i run features.ipynb , error is occuring. The program imports csv files;items and category from processed folder.,but they are not present there. I think some code is missing , in which items and category file was processed and these features were extracted.'meta_cat'

**Comment by rjfs** [comment]
Hi @abubakar12,
Thanks for reporting. I forgot to write that you should run _text_eda.ipynb_ before.
I fixed the readme file on this [commit](https://github.com/rjfs/kaggle/commit/0fe90fdd6535b06d3d4a875a1ab465981814e5db).
Let me know if you find any other problem.
